// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-_aJeUcA1bnGyRFd_anwdeTh2bzBbKo',
    appId: '1:927609487669:web:bc7eb2630cd9f343fd8c7c',
    messagingSenderId: '927609487669',
    projectId: 'delivery-app-template-2e43d',
    authDomain: 'delivery-app-template-2e43d.firebaseapp.com',
    storageBucket: 'delivery-app-template-2e43d.firebasestorage.app',
    measurementId: 'G-ZKNN5VYQDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTvLisKckv0Xy9HyD4i0qAaVkVFCGKa64',
    appId: '1:927609487669:android:775988abf5f7555afd8c7c',
    messagingSenderId: '927609487669',
    projectId: 'delivery-app-template-2e43d',
    storageBucket: 'delivery-app-template-2e43d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEvLvLi4aCkgLgrPFOAPyiJbdK7XecelE',
    appId: '1:927609487669:ios:b25c781e93cf83e4fd8c7c',
    messagingSenderId: '927609487669',
    projectId: 'delivery-app-template-2e43d',
    storageBucket: 'delivery-app-template-2e43d.firebasestorage.app',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD-_aJeUcA1bnGyRFd_anwdeTh2bzBbKo',
    appId: '1:927609487669:web:c1f0e0c07db067dcfd8c7c',
    messagingSenderId: '927609487669',
    projectId: 'delivery-app-template-2e43d',
    authDomain: 'delivery-app-template-2e43d.firebaseapp.com',
    storageBucket: 'delivery-app-template-2e43d.firebasestorage.app',
    measurementId: 'G-R50M6NZS16',
  );

}